// @Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
//
// Generates a human-readable Markdown compliance report from scan results.
// Structured for review by engineering leads and compliance officers, with
// executive summary, severity breakdown, per-repo findings, and remediation
// guidance.

import type {
  ComplianceFindingInput,
  AnalyzerResult,
  Severity,
} from "../types/index.js";

const SEVERITY_ORDER: Severity[] = [
  "CRITICAL",
  "HIGH",
  "MEDIUM",
  "LOW",
  "INFO",
];

/**
 * Generate a Markdown compliance report.
 */
export function generateMarkdownReport(opts: {
  scanId: string;
  framework: string;
  startedAt: string;
  completedAt: string | null;
  repos: string[];
  findings: ComplianceFindingInput[];
  analyzerResults: AnalyzerResult[];
  totalFilesScanned: number;
}): string {
  const {
    scanId,
    framework,
    startedAt,
    completedAt,
    repos,
    findings,
    analyzerResults,
    totalFilesScanned,
  } = opts;

  const lines: string[] = [];

  // Header
  lines.push("# Compliance Scan Report");
  lines.push("");
  lines.push(`**Scan ID:** \`${scanId}\``);
  lines.push(`**Date:** ${startedAt}`);
  if (completedAt) {
    lines.push(`**Completed:** ${completedAt}`);
  }
  lines.push(
    `**Framework:** ${framework === "both" ? "SOC2 + HIPAA" : framework.toUpperCase()}`,
  );
  lines.push(`**Repos scanned:** ${repos.length}`);
  lines.push(`**Files scanned:** ${totalFilesScanned}`);
  lines.push(`**Total findings:** ${findings.length}`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  const bySeverity: Record<string, number> = {};
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
  }
  for (const sev of SEVERITY_ORDER) {
    const count = bySeverity[sev] ?? 0;
    if (count > 0) {
      lines.push(`| ${sev} | ${count} |`);
    }
  }
  lines.push("");

  // Analyzer performance
  lines.push("## Analyzer Performance");
  lines.push("");
  lines.push("| Analyzer | Findings | Files | Duration |");
  lines.push("|----------|----------|-------|----------|");
  for (const ar of analyzerResults) {
    lines.push(
      `| ${ar.analyzerName} | ${ar.findings.length} | ${ar.filesScanned} | ${ar.durationMs}ms |`,
    );
  }
  lines.push("");

  // Findings by repository
  lines.push("## Findings by Repository");
  lines.push("");

  // Group findings by repo, then by severity
  const findingsByRepo: Record<string, ComplianceFindingInput[]> = {};
  for (const f of findings) {
    if (!findingsByRepo[f.repo]) {
      findingsByRepo[f.repo] = [];
    }
    findingsByRepo[f.repo].push(f);
  }

  // Sort repos by total findings (most first)
  const sortedRepos = Object.entries(findingsByRepo).sort(
    ([, a], [, b]) => b.length - a.length,
  );

  for (const [repo, repoFindings] of sortedRepos) {
    lines.push(`### ${repo}`);
    lines.push("");
    lines.push(`*${repoFindings.length} finding(s)*`);
    lines.push("");

    // Sort findings by severity
    const sorted = [...repoFindings].sort(
      (a, b) =>
        SEVERITY_ORDER.indexOf(a.severity as Severity) -
        SEVERITY_ORDER.indexOf(b.severity as Severity),
    );

    for (const finding of sorted) {
      lines.push(
        `#### ${finding.severity}: ${finding.title}`,
      );
      lines.push("");
      lines.push(
        `**File:** \`${finding.filePath}${finding.lineNumber ? `:${finding.lineNumber}` : ""}\``,
      );
      lines.push(`**Analyzer:** ${finding.analyzer}`);
      lines.push(`**Framework:** ${finding.framework.toUpperCase()}`);
      lines.push("");
      lines.push(finding.description);
      lines.push("");

      if (finding.snippet) {
        lines.push("**Code:**");
        lines.push("```typescript");
        lines.push(finding.snippet);
        lines.push("```");
        lines.push("");
      }

      if (finding.remediation) {
        lines.push(`**Remediation:** ${finding.remediation}`);
        lines.push("");
      }

      lines.push("---");
      lines.push("");
    }
  }

  // Repos with no findings
  const cleanRepos = repos.filter((r) => !findingsByRepo[r]);
  if (cleanRepos.length > 0) {
    lines.push("## Clean Repositories");
    lines.push("");
    lines.push(
      "The following repositories had no compliance findings:",
    );
    lines.push("");
    for (const repo of cleanRepos) {
      lines.push(`- ${repo}`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by compliance-auditor | @Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology*",
  );

  return lines.join("\n");
}
