// @Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
//
// Ground truth dataset of correct matches with expected confidence scores.
// 25 test cases covering exact title matches, description keyword matches,
// PR title to invoice line matching, and category-based matching.

import type { ConfidenceTestCase, MatchPair } from "../types/index.js";

/**
 * Known-good match pairs: invoice line items that should match their
 * corresponding Linear issues or GitHub PRs with high confidence.
 */
export const KNOWN_GOOD_MATCH_PAIRS: MatchPair[] = [
  {
    invoiceLineNumber: 1,
    invoiceDescription: "Implement user authentication feature",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-101",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 2,
    invoiceDescription: "Fix memory leak bug in auth module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-102",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 3,
    invoiceDescription: "Code review for dashboard analytics PR",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-201",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 4,
    invoiceDescription: "Deploy payment processing to staging",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-103",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 5,
    invoiceDescription: "Write E2E tests for notification system",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-104",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 6,
    invoiceDescription: "Sprint planning meeting",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-105",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 7,
    invoiceDescription: "Design search functionality UI mockups in Figma",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-106",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 8,
    invoiceDescription: "Build file upload integration",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-202",
    expectedMatch: true,
    expectedConfidence: 0.95,
  },
  {
    invoiceLineNumber: 9,
    invoiceDescription: "Hotfix: timeout crash on API gateway",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-107",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 10,
    invoiceDescription: "CI pipeline fix for middleware stack",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-203",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 11,
    invoiceDescription: "Develop report generation module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-108",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 12,
    invoiceDescription: "QA testing: user onboarding module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-109",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 13,
    invoiceDescription: "Configure deployment pipeline",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-204",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 14,
    invoiceDescription: "PR review: API rate limiting implementation",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-205",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 15,
    invoiceDescription: "Weekly standup call",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-110",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 16,
    invoiceDescription: "Implement webhook handler",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-111",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 17,
    invoiceDescription: "Resolve validation issue in billing module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-112",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 18,
    invoiceDescription: "Update Figma designs for admin panel",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-113",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 19,
    invoiceDescription: "Unit test coverage for queue processor",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-114",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 20,
    invoiceDescription: "Implement data export functionality",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-206",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 21,
    invoiceDescription: "Client call: role-based access requirements",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-115",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 22,
    invoiceDescription: "Develop audit logging feature",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-116",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 23,
    invoiceDescription: "Fix encoding bug in file service",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-207",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 24,
    invoiceDescription: "Build email templates integration",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-117",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
  {
    invoiceLineNumber: 25,
    invoiceDescription: "Deploy caching layer to staging",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-118",
    expectedMatch: true,
    expectedConfidence: 1.0,
  },
];

/**
 * Confidence test cases for known-good matches.
 * These validate that exact and near-exact matches produce high confidence scores.
 */
export const KNOWN_GOOD_CONFIDENCE_CASES: ConfidenceTestCase[] = [
  {
    description: "Exact match: identical descriptions",
    invoiceDescription: "Implement user authentication feature",
    entityTitle: "Implement user authentication feature",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: bug fix description",
    invoiceDescription: "Fix memory leak bug in auth module",
    entityTitle: "Fix memory leak bug in auth module",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: PR prefix added",
    invoiceDescription: "Build file upload integration",
    entityTitle: "feat: build file upload integration",
    entityType: "github_pr",
    expectedMinConfidence: 0.85,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: slight rewording",
    invoiceDescription: "Deploy payment processing to staging",
    entityTitle: "Deploy payment processing to staging environment",
    entityType: "linear_issue",
    expectedMinConfidence: 0.85,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: meeting description",
    invoiceDescription: "Sprint planning meeting",
    entityTitle: "Sprint planning meeting",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: keyword overlap with reorder",
    invoiceDescription: "Write E2E tests for notification system",
    entityTitle: "E2E tests for notification system",
    entityType: "linear_issue",
    expectedMinConfidence: 0.85,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: code review description",
    invoiceDescription: "Code review for dashboard analytics PR",
    entityTitle: "Code review for dashboard analytics PR",
    entityType: "github_pr",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: PR title convention",
    invoiceDescription: "CI pipeline fix for middleware stack",
    entityTitle: "fix: CI pipeline for middleware stack",
    entityType: "github_pr",
    expectedMinConfidence: 0.80,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: design task",
    invoiceDescription: "Design search functionality UI mockups in Figma",
    entityTitle: "Design search functionality UI mockups in Figma",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: hotfix description",
    invoiceDescription: "Hotfix: timeout crash on API gateway",
    entityTitle: "Hotfix: timeout crash on API gateway",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: different verb form",
    invoiceDescription: "Develop report generation module",
    entityTitle: "Report generation module development",
    entityType: "linear_issue",
    expectedMinConfidence: 0.50,
    expectedMaxConfidence: 0.94,
  },
  {
    description: "Near-exact match: abbreviation difference",
    invoiceDescription: "QA testing: user onboarding module",
    entityTitle: "QA testing user onboarding module",
    entityType: "linear_issue",
    expectedMinConfidence: 0.85,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: deployment task",
    invoiceDescription: "Configure deployment pipeline",
    entityTitle: "Configure deployment pipeline",
    entityType: "github_pr",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: PR review with prefix",
    invoiceDescription: "PR review: API rate limiting implementation",
    entityTitle: "feat: API rate limiting implementation",
    entityType: "github_pr",
    expectedMinConfidence: 0.50,
    expectedMaxConfidence: 0.94,
  },
  {
    description: "Exact match: standup call",
    invoiceDescription: "Weekly standup call",
    entityTitle: "Weekly standup call",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: webhook handler",
    invoiceDescription: "Implement webhook handler",
    entityTitle: "feat: implement webhook handler",
    entityType: "linear_issue",
    expectedMinConfidence: 0.85,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: issue resolution",
    invoiceDescription: "Resolve validation issue in billing module",
    entityTitle: "Resolve validation issue in billing module",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: Figma designs",
    invoiceDescription: "Update Figma designs for admin panel",
    entityTitle: "Update Figma designs for admin panel",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Exact match: unit test coverage",
    invoiceDescription: "Unit test coverage for queue processor",
    entityTitle: "Unit test coverage for queue processor",
    entityType: "linear_issue",
    expectedMinConfidence: 0.95,
    expectedMaxConfidence: 1.0,
  },
  {
    description: "Near-exact match: data export PR",
    invoiceDescription: "Implement data export functionality",
    entityTitle: "feat: data export functionality",
    entityType: "github_pr",
    expectedMinConfidence: 0.50,
    expectedMaxConfidence: 0.94,
  },
];
