// @Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
//
// Ground truth dataset of intentional non-matches. 20 test cases covering
// similar but different descriptions, different projects, date range
// mismatches, and different contractors.

import type { ConfidenceTestCase, MatchPair } from "../types/index.js";

/**
 * Known-bad match pairs: invoice line items that should NOT match the
 * given Linear issues or GitHub PRs. The reconciliation algorithm should
 * correctly identify these as non-matches.
 */
export const KNOWN_BAD_MATCH_PAIRS: MatchPair[] = [
  {
    invoiceLineNumber: 1,
    invoiceDescription: "Implement user authentication feature",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-200",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 2,
    invoiceDescription: "Fix memory leak bug in auth module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-201",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 3,
    invoiceDescription: "Code review for dashboard analytics PR",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-300",
    expectedMatch: false,
    expectedConfidence: 0.08,
  },
  {
    invoiceLineNumber: 4,
    invoiceDescription: "Deploy payment processing to staging",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-202",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 5,
    invoiceDescription: "Write E2E tests for notification system",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-301",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 6,
    invoiceDescription: "Sprint planning meeting",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-203",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 7,
    invoiceDescription: "Design search functionality UI mockups in Figma",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-204",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 8,
    invoiceDescription: "Build file upload integration",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-302",
    expectedMatch: false,
    expectedConfidence: 0.08,
  },
  {
    invoiceLineNumber: 9,
    invoiceDescription: "Hotfix: timeout crash on API gateway",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-205",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 10,
    invoiceDescription: "CI pipeline fix for middleware stack",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-303",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 11,
    invoiceDescription: "Develop report generation module",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-206",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 12,
    invoiceDescription: "QA testing: user onboarding module",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-304",
    expectedMatch: false,
    expectedConfidence: 0.08,
  },
  {
    invoiceLineNumber: 13,
    invoiceDescription: "Configure deployment pipeline",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-207",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 14,
    invoiceDescription: "PR review: API rate limiting implementation",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-305",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 15,
    invoiceDescription: "Weekly standup call",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-208",
    expectedMatch: false,
    expectedConfidence: 0.08,
  },
  {
    invoiceLineNumber: 16,
    invoiceDescription: "Implement webhook handler",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-209",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 17,
    invoiceDescription: "Resolve validation issue in billing module",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-306",
    expectedMatch: false,
    expectedConfidence: 0.1,
  },
  {
    invoiceLineNumber: 18,
    invoiceDescription: "Update Figma designs for admin panel",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-210",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
  {
    invoiceLineNumber: 19,
    invoiceDescription: "Unit test coverage for queue processor",
    matchedEntityType: "github_pr",
    matchedEntityId: "PR-307",
    expectedMatch: false,
    expectedConfidence: 0.08,
  },
  {
    invoiceLineNumber: 20,
    invoiceDescription: "Implement data export functionality",
    matchedEntityType: "linear_issue",
    matchedEntityId: "GBS-211",
    expectedMatch: false,
    expectedConfidence: 0.05,
  },
];

/**
 * Confidence test cases for known-bad matches. The invoice descriptions and
 * entity titles are deliberately different -- the reconciliation algorithm
 * should produce low confidence scores for these pairs.
 */
export const KNOWN_BAD_CONFIDENCE_CASES: ConfidenceTestCase[] = [
  {
    description: "No match: auth feature vs database migration",
    invoiceDescription: "Implement user authentication feature",
    entityTitle: "Migrate PostgreSQL schema to version 12",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: memory leak fix vs dependency update",
    invoiceDescription: "Fix memory leak bug in auth module",
    entityTitle: "chore: bump dependencies to latest versions",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: dashboard review vs Docker config",
    invoiceDescription: "Code review for dashboard analytics PR",
    entityTitle: "Update Docker base image to Node 22",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: payment deploy vs security audit",
    invoiceDescription: "Deploy payment processing to staging",
    entityTitle: "Audit security headers across all endpoints",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: E2E tests vs ESLint config",
    invoiceDescription: "Write E2E tests for notification system",
    entityTitle: "Configure ESLint flat config for monorepo",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: sprint planning vs Redis caching",
    invoiceDescription: "Sprint planning meeting",
    entityTitle: "Implement Redis caching layer for sessions",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: Figma design vs database backup",
    invoiceDescription: "Design search functionality UI mockups in Figma",
    entityTitle: "Set up automated database backups to GCS",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: file upload vs bundle optimization",
    invoiceDescription: "Build file upload integration",
    entityTitle: "perf: optimize production bundle size",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: API timeout vs SSO integration",
    invoiceDescription: "Hotfix: timeout crash on API gateway",
    entityTitle: "Integrate Azure AD SSO for enterprise users",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: CI pipeline vs onboarding wireframes",
    invoiceDescription: "CI pipeline fix for middleware stack",
    entityTitle: "Design new onboarding flow wireframes",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: report generation vs image processing",
    invoiceDescription: "Develop report generation module",
    entityTitle: "Optimize image processing pipeline latency",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: QA onboarding vs error tracking",
    invoiceDescription: "QA testing: user onboarding module",
    entityTitle: "Integrate Sentry error tracking in production",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: deployment pipeline vs API documentation",
    invoiceDescription: "Configure deployment pipeline",
    entityTitle: "Write comprehensive internal API documentation",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: rate limiting vs memory investigation",
    invoiceDescription: "PR review: API rate limiting implementation",
    entityTitle: "Investigate worker process memory consumption",
    entityType: "github_pr",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
  {
    description: "No match: standup vs Prettier formatting",
    invoiceDescription: "Weekly standup call",
    entityTitle: "style: apply Prettier formatting across workspace",
    entityType: "linear_issue",
    expectedMinConfidence: 0.0,
    expectedMaxConfidence: 0.19,
  },
];
