"""Evidence-backed financial domains that complete the synthetic case ledger.

The money spine records wages, indemnity payments, and settlement funding. This
module records the adjacent facts needed to generate and score a complete case:
rating, carrier reserves, settlement disbursement, provider billing, and penalty
exposure. Every domain is opt-in through ``scenario.financials`` so historical
seeds retain their exact output.

The module intentionally separates arithmetic from legal authority. It can
reconcile dollars exactly, but a rating method or penalty rate is only legally
confirmed when the seed says so and supplies confirmed authority.

@Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
"""

from __future__ import annotations

import datetime as dt
from decimal import Decimal, ROUND_HALF_UP, localcontext
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

CENTS = Decimal("0.01")
ZERO = Decimal("0.00")
UNCONFIRMED_AUTHORITY = "COUNSEL-UNCONFIRMED: synthetic training assumption"


def money(value: Decimal | int | float | str) -> Decimal:
    """Return a cents-quantized decimal without inheriting caller precision."""
    with localcontext() as context:
        context.prec = 28
        return Decimal(str(value)).quantize(CENTS, rounding=ROUND_HALF_UP)


def _dollars(value: Decimal) -> str:
    return f"{money(value):.2f}"


class _Scenario(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class _Fact(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class RatingScenario(_Scenario):
    """A rating supplied by the seed or completed from the internal case ledger."""

    wpi: int | None = Field(default=None, ge=0, le=100)
    pd_percent: int | None = Field(default=None, ge=0, le=100)
    method: str = "engine_training_heuristic"
    authority: str = UNCONFIRMED_AUTHORITY
    counsel_confirmed: bool = False

    @model_validator(mode="after")
    def _confirmed_authority_is_real(self) -> RatingScenario:
        if self.counsel_confirmed and "UNCONFIRMED" in self.authority.upper():
            raise ValueError(
                "scenario.financials.rating.counsel_confirmed is true but authority is "
                "still marked unconfirmed. Supply confirmed authority or set the flag false."
            )
        return self


class ReserveChangeScenario(_Scenario):
    """Absolute reserve balances after one case event, not ambiguous deltas."""

    event_date: dt.date
    reason: str
    medical: Decimal | None = Field(default=None, ge=0)
    indemnity: Decimal | None = Field(default=None, ge=0)
    expense: Decimal | None = Field(default=None, ge=0)


class ReserveScenario(_Scenario):
    """Carrier reserve controls.

    Omitted opening categories are derived from already-generated exposure and
    labelled as engine estimates. Seeded changes are absolute balances so a
    reader can reproduce every total without guessing whether a number was a
    delta or a replacement.
    """

    medical: Decimal | None = Field(default=None, ge=0)
    indemnity: Decimal | None = Field(default=None, ge=0)
    expense: Decimal | None = Field(default=None, ge=0)
    changes: list[ReserveChangeScenario] = Field(default_factory=list, max_length=50)


type DisbursementCategory = Literal[
    "attorney_fee", "lien", "cost", "msa", "other", "applicant_net"
]


class DisbursementItemScenario(_Scenario):
    payee: str
    category: Literal["attorney_fee", "lien", "cost", "msa", "other"]
    amount: Decimal = Field(ge=0)
    paid_date: dt.date | None = None
    reference: str | None = None


class DisbursementScenario(_Scenario):
    """Seeded deductions from gross settlement.

    The applicant-net line is never seeded. It is the exact remainder and is
    generated by reconciliation, which prevents a plausible-looking schedule
    whose rows do not add back to the settlement.
    """

    items: list[DisbursementItemScenario] = Field(default_factory=list, max_length=100)


class BillingLineScenario(_Scenario):
    invoice_id: str
    provider: str
    service_date: dt.date
    charge: Decimal = Field(ge=0)
    paid: Decimal = Field(default=ZERO, ge=0)
    adjustment: Decimal = Field(default=ZERO, ge=0)
    lien_amount: Decimal = Field(default=ZERO, ge=0)
    cpt_codes: list[str] = Field(default_factory=list, max_length=40)

    @model_validator(mode="after")
    def _line_reconciles(self) -> BillingLineScenario:
        if money(self.paid + self.adjustment) > money(self.charge):
            raise ValueError(
                f"billing invoice {self.invoice_id!r} pays/adjusts more than its charge"
            )
        outstanding = money(self.charge - self.paid - self.adjustment)
        if money(self.lien_amount) > outstanding:
            raise ValueError(
                f"billing invoice {self.invoice_id!r} has lien_amount above its "
                "outstanding balance"
            )
        return self


class BillingScenario(_Scenario):
    lines: list[BillingLineScenario] = Field(default_factory=list, max_length=500)

    @model_validator(mode="after")
    def _invoice_ids_are_unique(self) -> BillingScenario:
        ids = [line.invoice_id for line in self.lines]
        duplicates = sorted({value for value in ids if ids.count(value) > 1})
        if duplicates:
            raise ValueError(
                "scenario.financials.billing has duplicate invoice_id values: "
                + ", ".join(duplicates)
            )
        return self


class PenaltyScenario(_Scenario):
    """The seed-authored legal rate applied to recoverable late transactions."""

    rate: Decimal = Field(gt=0, le=1)
    authority: str = UNCONFIRMED_AUTHORITY
    counsel_confirmed: bool = False
    assessed_date: dt.date | None = None

    @model_validator(mode="after")
    def _confirmed_authority_is_real(self) -> PenaltyScenario:
        if self.counsel_confirmed and "UNCONFIRMED" in self.authority.upper():
            raise ValueError(
                "scenario.financials.penalties.counsel_confirmed is true but authority "
                "is still marked unconfirmed. Supply confirmed authority or set the flag false."
            )
        return self


class FinancialScenario(_Scenario):
    """Opt-in seed contract for the five post-money financial domains."""

    rating: RatingScenario | None = None
    reserves: ReserveScenario | None = None
    disbursement: DisbursementScenario | None = None
    billing: BillingScenario | None = None
    penalties: PenaltyScenario | None = None

    @model_validator(mode="after")
    def _contains_a_domain(self) -> FinancialScenario:
        if not any(
            value is not None
            for value in (
                self.rating,
                self.reserves,
                self.disbursement,
                self.billing,
                self.penalties,
            )
        ):
            raise ValueError(
                "scenario.financials must configure at least one of rating, reserves, "
                "disbursement, billing, or penalties"
            )
        return self


class RatingFacts(_Fact):
    wpi: int
    pd_percent: int
    method: str
    authority: str
    counsel_confirmed: bool
    source: Literal["seed", "engine_training_heuristic", "mixed"]


class ReserveEntry(_Fact):
    event_date: dt.date
    reason: str
    medical: Decimal
    indemnity: Decimal
    expense: Decimal
    total: Decimal
    source: Literal["seed", "engine_estimate", "mixed"]


class ReserveLedger(_Fact):
    entries: tuple[ReserveEntry, ...] = ()

    @property
    def current(self) -> ReserveEntry | None:
        return self.entries[-1] if self.entries else None


class DisbursementItem(_Fact):
    payee: str
    category: DisbursementCategory
    amount: Decimal
    paid_date: dt.date | None = None
    reference: str | None = None


class DisbursementLedger(_Fact):
    gross_amount: Decimal
    items: tuple[DisbursementItem, ...]
    total_disbursed: Decimal
    applicant_net: Decimal
    reconciled: bool


class BillingLine(_Fact):
    invoice_id: str
    provider: str
    service_date: dt.date
    charge: Decimal
    paid: Decimal
    adjustment: Decimal
    outstanding: Decimal
    lien_amount: Decimal
    cpt_codes: tuple[str, ...] = ()


class BillingLedger(_Fact):
    lines: tuple[BillingLine, ...] = ()
    total_charged: Decimal = ZERO
    total_paid: Decimal = ZERO
    total_adjusted: Decimal = ZERO
    total_outstanding: Decimal = ZERO
    total_liens: Decimal = ZERO


class PenaltyExposure(_Fact):
    source: str
    principal: Decimal
    days_late: int
    rate: Decimal
    amount: Decimal
    authority: str
    counsel_confirmed: bool
    assessed_date: dt.date | None = None


class PenaltyLedger(_Fact):
    exposures: tuple[PenaltyExposure, ...] = ()
    total_exposure: Decimal = ZERO


class FinancialFacts(_Fact):
    """Resolved facts for every configured post-money financial domain."""

    rating: RatingFacts | None = None
    reserves: ReserveLedger | None = None
    disbursement: DisbursementLedger | None = None
    billing: BillingLedger | None = None
    penalties: PenaltyLedger | None = None


def _sum(values: Any) -> Decimal:
    with localcontext() as context:
        context.prec = 28
        return money(sum((Decimal(value) for value in values), ZERO))


def _derive_rating(scenario: RatingScenario, case_facts: Any) -> RatingFacts | None:
    ledger_wpi = getattr(case_facts, "wpi", None)
    ledger_pd = getattr(case_facts, "pd", None)
    wpi = scenario.wpi if scenario.wpi is not None else ledger_wpi
    pd = scenario.pd_percent if scenario.pd_percent is not None else ledger_pd
    if wpi is None or pd is None:
        return None
    authored = (scenario.wpi is not None, scenario.pd_percent is not None)
    source: Literal["seed", "engine_training_heuristic", "mixed"]
    source = "seed" if all(authored) else "mixed" if any(authored) else "engine_training_heuristic"
    return RatingFacts(
        wpi=wpi,
        pd_percent=pd,
        method=scenario.method,
        authority=scenario.authority,
        counsel_confirmed=scenario.counsel_confirmed,
        source=source,
    )


def _derive_billing(scenario: BillingScenario) -> BillingLedger:
    lines = tuple(
        BillingLine(
            invoice_id=line.invoice_id,
            provider=line.provider,
            service_date=line.service_date,
            charge=money(line.charge),
            paid=money(line.paid),
            adjustment=money(line.adjustment),
            outstanding=money(line.charge - line.paid - line.adjustment),
            lien_amount=money(line.lien_amount),
            cpt_codes=tuple(line.cpt_codes),
        )
        for line in scenario.lines
    )
    return BillingLedger(
        lines=lines,
        total_charged=_sum(line.charge for line in lines),
        total_paid=_sum(line.paid for line in lines),
        total_adjusted=_sum(line.adjustment for line in lines),
        total_outstanding=_sum(line.outstanding for line in lines),
        total_liens=_sum(line.lien_amount for line in lines),
    )


def _derive_reserves(
    scenario: ReserveScenario,
    money_facts: Any,
    billing: BillingLedger | None,
    timeline: Any,
) -> ReserveLedger:
    benefits = money_facts.benefits
    settlement = money_facts.settlement
    estimated_medical = billing.total_outstanding if billing is not None else ZERO
    paid_indemnity = money(benefits.td_total + benefits.pd_total)
    estimated_indemnity = max(
        paid_indemnity,
        money(settlement.gross_amount) if settlement is not None else ZERO,
    )
    medical = money(scenario.medical) if scenario.medical is not None else estimated_medical
    indemnity = (
        money(scenario.indemnity) if scenario.indemnity is not None else estimated_indemnity
    )
    expense = money(scenario.expense) if scenario.expense is not None else ZERO
    authored = (scenario.medical is not None, scenario.indemnity is not None, scenario.expense is not None)
    source: Literal["seed", "engine_estimate", "mixed"]
    source = "seed" if all(authored) else "mixed" if any(authored) else "engine_estimate"
    event_date = getattr(timeline, "claim_filed_date", None) or getattr(
        timeline, "injury_date", dt.date(2000, 1, 1)
    )
    entries = [
        ReserveEntry(
            event_date=event_date,
            reason="Opening reserve from configured values and published exposure",
            medical=medical,
            indemnity=indemnity,
            expense=expense,
            total=money(medical + indemnity + expense),
            source=source,
        )
    ]
    for change in sorted(scenario.changes, key=lambda item: item.event_date):
        previous = entries[-1]
        medical = money(change.medical) if change.medical is not None else previous.medical
        indemnity = (
            money(change.indemnity) if change.indemnity is not None else previous.indemnity
        )
        expense = money(change.expense) if change.expense is not None else previous.expense
        changed = (change.medical is not None, change.indemnity is not None, change.expense is not None)
        entries.append(
            ReserveEntry(
                event_date=change.event_date,
                reason=change.reason,
                medical=medical,
                indemnity=indemnity,
                expense=expense,
                total=money(medical + indemnity + expense),
                source="seed" if all(changed) else "mixed",
            )
        )
    return ReserveLedger(entries=tuple(entries))


def _derive_disbursement(
    scenario: DisbursementScenario, money_facts: Any
) -> DisbursementLedger | None:
    settlement = money_facts.settlement
    if settlement is None:
        return None
    gross = money(settlement.gross_amount)
    seeded = tuple(
        DisbursementItem(
            payee=item.payee,
            category=item.category,
            amount=money(item.amount),
            paid_date=item.paid_date,
            reference=item.reference,
        )
        for item in scenario.items
    )
    deductions = _sum(item.amount for item in seeded)
    if deductions > gross:
        raise ValueError(
            f"case settlement disbursements total ${deductions:.2f}, above gross "
            f"settlement ${gross:.2f}"
        )
    applicant_net = money(gross - deductions)
    items = seeded + (
        DisbursementItem(
            payee="Applicant",
            category="applicant_net",
            amount=applicant_net,
            paid_date=settlement.funding_date,
            reference="reconciled remainder of gross settlement",
        ),
    )
    total = _sum(item.amount for item in items)
    return DisbursementLedger(
        gross_amount=gross,
        items=items,
        total_disbursed=total,
        applicant_net=applicant_net,
        reconciled=total == gross,
    )


def _derive_penalties(scenario: PenaltyScenario, money_facts: Any) -> PenaltyLedger:
    exposures: list[PenaltyExposure] = []
    rate = Decimal(scenario.rate)
    for index, period in enumerate(money_facts.benefits.td_periods, start=1):
        if period.days_late <= 0 and period.date_paid is not None:
            continue
        exposures.append(
            PenaltyExposure(
                source=f"td_period:{index}",
                principal=money(period.amount),
                days_late=period.days_late,
                rate=rate,
                amount=money(period.amount * rate),
                authority=scenario.authority,
                counsel_confirmed=scenario.counsel_confirmed,
                assessed_date=scenario.assessed_date,
            )
        )
    for index, advance in enumerate(money_facts.benefits.pd_advances, start=1):
        if advance.days_late <= 0:
            continue
        exposures.append(
            PenaltyExposure(
                source=f"pd_advance:{index}",
                principal=money(advance.amount),
                days_late=advance.days_late,
                rate=rate,
                amount=money(advance.amount * rate),
                authority=scenario.authority,
                counsel_confirmed=scenario.counsel_confirmed,
                assessed_date=scenario.assessed_date,
            )
        )
    return PenaltyLedger(
        exposures=tuple(exposures),
        total_exposure=_sum(item.amount for item in exposures),
    )


def derive_financial_facts(
    seed: Any, case_facts: Any, money_facts: Any, timeline: Any
) -> FinancialFacts | None:
    """Resolve configured financial domains from one shared case/money ledger."""
    scenario: FinancialScenario | None = getattr(seed.scenario, "financials", None)
    if scenario is None or money_facts is None:
        return None

    billing = _derive_billing(scenario.billing) if scenario.billing is not None else None
    rating = (
        _derive_rating(scenario.rating, case_facts) if scenario.rating is not None else None
    )
    reserves = (
        _derive_reserves(scenario.reserves, money_facts, billing, timeline)
        if scenario.reserves is not None
        else None
    )
    disbursement = (
        _derive_disbursement(scenario.disbursement, money_facts)
        if scenario.disbursement is not None
        else None
    )
    penalties = (
        _derive_penalties(scenario.penalties, money_facts)
        if scenario.penalties is not None
        else None
    )
    return FinancialFacts(
        rating=rating,
        reserves=reserves,
        disbursement=disbursement,
        billing=billing,
        penalties=penalties,
    )


GOVERNED_FINANCIAL_FIELDS: dict[str, tuple[str, ...]] = {
    "rating": (
        "wpi",
        "pdPercent",
        "method",
        "authority",
        "counselConfirmed",
        "source",
    ),
    "reserves": (
        "entries",
        "eventDate",
        "reason",
        "medical",
        "indemnity",
        "expense",
        "total",
        "source",
    ),
    "disbursement": (
        "grossAmount",
        "items",
        "payee",
        "category",
        "amount",
        "paidDate",
        "reference",
        "totalDisbursed",
        "applicantNet",
        "reconciled",
    ),
    "billing": (
        "lines",
        "invoiceId",
        "provider",
        "serviceDate",
        "charge",
        "paid",
        "adjustment",
        "outstanding",
        "lienAmount",
        "cptCodes",
        "totals",
    ),
    "penalties": (
        "exposures",
        "source",
        "principal",
        "daysLate",
        "rate",
        "amount",
        "authority",
        "counselConfirmed",
        "assessedDate",
        "totalExposure",
    ),
}


def financial_manifest_block(facts: FinancialFacts) -> dict[str, Any]:
    """Serialize configured domains with exact money strings and authority flags."""
    block: dict[str, Any] = {}
    if facts.rating is not None:
        rating = facts.rating
        block["rating"] = {
            "wpi": rating.wpi,
            "pdPercent": rating.pd_percent,
            "method": rating.method,
            "authority": rating.authority,
            "counselConfirmed": rating.counsel_confirmed,
            "source": rating.source,
        }
    if facts.reserves is not None:
        block["reserves"] = {
            "entries": [
                {
                    "eventDate": entry.event_date.isoformat(),
                    "reason": entry.reason,
                    "medical": _dollars(entry.medical),
                    "indemnity": _dollars(entry.indemnity),
                    "expense": _dollars(entry.expense),
                    "total": _dollars(entry.total),
                    "source": entry.source,
                }
                for entry in facts.reserves.entries
            ]
        }
    if facts.disbursement is not None:
        ledger = facts.disbursement
        block["disbursement"] = {
            "grossAmount": _dollars(ledger.gross_amount),
            "items": [
                {
                    "payee": item.payee,
                    "category": item.category,
                    "amount": _dollars(item.amount),
                    "paidDate": item.paid_date.isoformat() if item.paid_date else None,
                    "reference": item.reference,
                }
                for item in ledger.items
            ],
            "totalDisbursed": _dollars(ledger.total_disbursed),
            "applicantNet": _dollars(ledger.applicant_net),
            "reconciled": ledger.reconciled,
        }
    if facts.billing is not None:
        ledger = facts.billing
        block["billing"] = {
            "lines": [
                {
                    "invoiceId": line.invoice_id,
                    "provider": line.provider,
                    "serviceDate": line.service_date.isoformat(),
                    "charge": _dollars(line.charge),
                    "paid": _dollars(line.paid),
                    "adjustment": _dollars(line.adjustment),
                    "outstanding": _dollars(line.outstanding),
                    "lienAmount": _dollars(line.lien_amount),
                    "cptCodes": list(line.cpt_codes),
                }
                for line in ledger.lines
            ],
            "totals": {
                "charged": _dollars(ledger.total_charged),
                "paid": _dollars(ledger.total_paid),
                "adjusted": _dollars(ledger.total_adjusted),
                "outstanding": _dollars(ledger.total_outstanding),
                "liens": _dollars(ledger.total_liens),
            },
        }
    if facts.penalties is not None:
        ledger = facts.penalties
        block["penalties"] = {
            "exposures": [
                {
                    "source": item.source,
                    "principal": _dollars(item.principal),
                    "daysLate": item.days_late,
                    "rate": f"{item.rate.normalize():f}",
                    "amount": _dollars(item.amount),
                    "authority": item.authority,
                    "counselConfirmed": item.counsel_confirmed,
                    "assessedDate": (
                        item.assessed_date.isoformat() if item.assessed_date else None
                    ),
                }
                for item in ledger.exposures
            ],
            "totalExposure": _dollars(ledger.total_exposure),
        }
    return block


__all__ = [
    "BillingLedger",
    "BillingLineScenario",
    "BillingScenario",
    "DisbursementItemScenario",
    "DisbursementLedger",
    "DisbursementScenario",
    "FinancialFacts",
    "FinancialScenario",
    "GOVERNED_FINANCIAL_FIELDS",
    "PenaltyLedger",
    "PenaltyScenario",
    "RatingFacts",
    "RatingScenario",
    "ReserveLedger",
    "ReserveScenario",
    "financial_manifest_block",
    "derive_financial_facts",
]
