/**
 * Log Writer Module
 *
 * Writes intelligence data to adjudica-documentation/logs/ via GitHub API.
 * Supports atomic file creation/update with YAML frontmatter and markdown content.
 *
 * Log Types:
 *   - commits: GitHub commit activity
 *   - prs: Pull request activity
 *   - deployments: GCP Cloud Run deployments
 *   - agents: Claude Code/Cursor session activity
 *   - checkpoints: Context window checkpoint events
 *   - analysis: Gemini-generated daily briefings
 *
 * @file log-writer.js
 * @module intelligence/log-writer
 *
 * @Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
 */

const { Octokit } = require('@octokit/rest');
const { retry } = require('@octokit/plugin-retry');
const { throttling } = require('@octokit/plugin-throttling');
const { GitHubAPIError, retryWithBackoff, formatDate, parseDate } = require('./utils');

// Create Octokit with retry and throttling plugins
const MyOctokit = Octokit.plugin(retry, throttling);

/**
 * Create configured Octokit client
 * @param {string} token - GitHub PAT
 * @returns {Octokit} - Configured Octokit instance
 */
function createOctokit(token) {
  return new MyOctokit({
    auth: token,
    throttle: {
      onRateLimit: (retryAfter, options, octokit, retryCount) => {
        console.warn(`Rate limit hit for ${options.method} ${options.url}`);
        console.warn(`Retry after ${retryAfter}s (attempt ${retryCount})`);

        // Retry first 3 times
        if (retryCount < 3) {
          return true;
        }
      },
      onSecondaryRateLimit: (retryAfter, options, octokit, retryCount) => {
        console.warn(`Secondary rate limit hit for ${options.method} ${options.url}`);
        // Always retry secondary rate limits
        return true;
      }
    },
    retry: {
      doNotRetry: [400, 401, 403, 404, 422]
    }
  });
}

/**
 * Generate YAML frontmatter for log files
 * @param {string} date - YYYY-MM-DD date string
 * @param {string} logType - Type of log
 * @param {Array<string>} sources - Data sources
 * @returns {string} - YAML frontmatter
 */
function generateFrontmatter(date, logType, sources = ['github', 'gcp_logging', 'station_monitor']) {
  const now = new Date().toISOString();
  return `---
generated_by: squeegee
date: ${date}
log_type: ${logType}
generated_at: ${now}
sources:
${sources.map(s => `  - ${s}`).join('\n')}
---`;
}

/**
 * Format commit data as markdown
 * @param {Object} data - GitHub activity data
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatCommitsLog(data, date) {
  const frontmatter = generateFrontmatter(date, 'commits', ['github']);
  const { repos, summary } = data;

  let markdown = `${frontmatter}

# GitHub Commit Activity - ${date}

## Summary

- **Total Commits**: ${summary.total_commits}
- **Repos Active**: ${Object.keys(repos).length}
- **Repos Monitored**: ${Object.keys(repos).length}
`;

  // Find top contributor
  const authorCounts = {};
  for (const repoData of Object.values(repos)) {
    for (const commit of repoData.commits) {
      const author = commit.author;
      authorCounts[author] = (authorCounts[author] || 0) + 1;
    }
  }

  const topContributor = Object.entries(authorCounts)
    .sort((a, b) => b[1] - a[1])[0];

  if (topContributor) {
    markdown += `- **Top Contributor**: ${topContributor[0]} (${topContributor[1]} commits)\n`;
  }

  markdown += '\n## By Repository\n\n';

  // Add commits by repository
  const reposWithCommits = Object.entries(repos)
    .filter(([_, repoData]) => repoData.commits.length > 0)
    .sort((a, b) => b[1].commits.length - a[1].commits.length);

  if (reposWithCommits.length === 0) {
    markdown += '*No commits on this date.*\n';
  } else {
    for (const [repo, repoData] of reposWithCommits) {
      markdown += `### ${repo} (${repoData.commits.length} commits)\n\n`;

      for (const commit of repoData.commits.slice(0, 10)) { // First 10 commits per repo
        const shortSha = commit.sha.substring(0, 7);
        markdown += `- [\`${shortSha}\`] ${commit.message} - ${commit.author}\n`;
      }

      if (repoData.commits.length > 10) {
        markdown += `\n*... and ${repoData.commits.length - 10} more commits*\n`;
      }

      markdown += '\n';
    }
  }

  markdown += `---

*Generated by Squeegee Intelligence System on ${new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Format pull request data as markdown
 * @param {Object} data - GitHub activity data
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatPRsLog(data, date) {
  const frontmatter = generateFrontmatter(date, 'prs', ['github']);
  const { repos, summary } = data;

  let markdown = `${frontmatter}

# GitHub Pull Request Activity - ${date}

## Summary

- **Total PRs**: ${summary.total_prs}
- **Repos Active**: ${Object.values(repos).filter(r => r.pull_requests.length > 0).length}
`;

  // Count by state
  let mergedCount = 0;
  let openCount = 0;
  let closedCount = 0;

  for (const repoData of Object.values(repos)) {
    for (const pr of repoData.pull_requests) {
      if (pr.state === 'merged') mergedCount++;
      else if (pr.state === 'open') openCount++;
      else if (pr.state === 'closed') closedCount++;
    }
  }

  markdown += `- **Merged**: ${mergedCount}\n`;
  markdown += `- **Opened**: ${openCount}\n`;
  markdown += `- **Closed**: ${closedCount}\n`;

  markdown += '\n## By Repository\n\n';

  // Add PRs by repository
  const reposWithPRs = Object.entries(repos)
    .filter(([_, repoData]) => repoData.pull_requests.length > 0)
    .sort((a, b) => b[1].pull_requests.length - a[1].pull_requests.length);

  if (reposWithPRs.length === 0) {
    markdown += '*No pull request activity on this date.*\n';
  } else {
    for (const [repo, repoData] of reposWithPRs) {
      markdown += `### ${repo} (${repoData.pull_requests.length} PRs)\n\n`;

      for (const pr of repoData.pull_requests) {
        const labels = pr.labels.length > 0 ? ` [${pr.labels.join(', ')}]` : '';
        const stateEmoji = pr.state === 'merged' ? '✅' : pr.state === 'open' ? '🟢' : '❌';
        markdown += `- ${stateEmoji} #${pr.number}: ${pr.title}${labels} - @${pr.author}\n`;
      }

      markdown += '\n';
    }
  }

  markdown += `---

*Generated by Squeegee Intelligence System on ${new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Format deployment data as markdown
 * @param {Object} data - GCP activity data
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatDeploymentsLog(data, date) {
  const frontmatter = generateFrontmatter(date, 'deployments', ['gcp_logging']);
  const { deployments = [], summary = {} } = data;

  let markdown = `${frontmatter}

# GCP Cloud Run Deployments - ${date}

## Summary

- **Total Deployments**: ${summary.total_deployments || 0}
- **Projects Monitored**: ${summary.projects_monitored || 0}
`;

  // Count successes vs failures
  const successCount = deployments.filter(d => d.status === 'success').length;
  const failureCount = deployments.filter(d => d.status === 'failed').length;

  markdown += `- **Successful**: ${successCount}\n`;
  markdown += `- **Failed**: ${failureCount}\n`;

  markdown += '\n## Deployment Events\n\n';

  if (deployments.length === 0) {
    markdown += '*No deployments on this date.*\n';
  } else {
    // Group by project
    const byProject = {};
    for (const deployment of deployments) {
      if (!byProject[deployment.project]) {
        byProject[deployment.project] = [];
      }
      byProject[deployment.project].push(deployment);
    }

    for (const [project, projectDeployments] of Object.entries(byProject)) {
      markdown += `### ${project}\n\n`;

      for (const deployment of projectDeployments) {
        const statusEmoji = deployment.status === 'success' ? '✅' : '❌';
        const timestamp = new Date(deployment.timestamp).toISOString();
        markdown += `- ${statusEmoji} **${deployment.service}** (${deployment.revision}) - ${timestamp}\n`;
      }

      markdown += '\n';
    }
  }

  markdown += `---

*Generated by Squeegee Intelligence System on ${new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Format agent activity data as markdown
 * @param {Object} data - Station activity data
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatAgentsLog(data, date) {
  const frontmatter = generateFrontmatter(date, 'agents', ['station_monitor']);
  const { claude_code_sessions = [], cursor_active = false, squeegee_state = {} } = data;

  let markdown = `${frontmatter}

# Development Agent Activity - ${date}

## Summary

- **Claude Code Sessions**: ${claude_code_sessions.length}
- **Cursor Active**: ${cursor_active ? 'Yes' : 'No'}
- **Squeegee State**: ${squeegee_state.last_run ? 'Running' : 'Idle'}
`;

  if (squeegee_state.last_run) {
    markdown += `- **Last Squeegee Run**: ${squeegee_state.last_run}\n`;
    markdown += `- **Repos Processed**: ${squeegee_state.repos_processed || 0}\n`;
  }

  markdown += '\n## Claude Code Sessions\n\n';

  if (claude_code_sessions.length === 0) {
    markdown += '*No Claude Code sessions detected.*\n';
  } else {
    for (const session of claude_code_sessions) {
      markdown += `### ${session.project_name}\n\n`;
      markdown += `- **Session ID**: ${session.session_id}\n`;
      markdown += `- **Memory Files**: ${session.memory_files_count}\n`;
      markdown += `- **Estimated Tokens**: ${session.estimated_tokens.toLocaleString()}\n\n`;
    }
  }

  markdown += '## Cursor Activity\n\n';
  markdown += cursor_active
    ? '*Cursor workspace detected - IDE active on workstation.*\n'
    : '*No Cursor activity detected.*\n';

  markdown += `\n---

*Generated by Squeegee Intelligence System on ${new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Format checkpoint data as markdown
 * @param {Array} checkpoints - Checkpoint events
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatCheckpointsLog(checkpoints, date) {
  const frontmatter = generateFrontmatter(date, 'checkpoints', ['station_monitor']);

  let markdown = `${frontmatter}

# Context Checkpoint Events - ${date}

## Summary

- **Total Checkpoints**: ${checkpoints.length}
`;

  if (checkpoints.length > 0) {
    const uniqueRepos = [...new Set(checkpoints.map(c => c.repo))];
    const uniqueUsers = [...new Set(checkpoints.map(c => c.user))];
    markdown += `- **Repos**: ${uniqueRepos.length}\n`;
    markdown += `- **Users**: ${uniqueUsers.length}\n`;
  }

  markdown += '\n## Checkpoint Events\n\n';

  if (checkpoints.length === 0) {
    markdown += '*No checkpoint events on this date.*\n';
  } else {
    // Group by repo
    const byRepo = {};
    for (const checkpoint of checkpoints) {
      if (!byRepo[checkpoint.repo]) {
        byRepo[checkpoint.repo] = [];
      }
      byRepo[checkpoint.repo].push(checkpoint);
    }

    for (const [repo, repoCheckpoints] of Object.entries(byRepo)) {
      markdown += `### ${repo}\n\n`;

      for (const checkpoint of repoCheckpoints) {
        const timestamp = new Date(checkpoint.timestamp).toISOString();
        markdown += `#### ${timestamp} - @${checkpoint.user}\n\n`;
        if (checkpoint.phase) markdown += `- **Phase**: ${checkpoint.phase}\n`;
        markdown += `- **Context Window**: ${checkpoint.context_pct}%\n`;
        if (checkpoint.completed) markdown += `- **Completed**: ${checkpoint.completed}\n`;
        if (checkpoint.next) markdown += `- **Next**: ${checkpoint.next}\n`;
        markdown += '\n';
      }
    }
  }

  markdown += `---

*Generated by Squeegee Intelligence System on ${new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Format Gemini briefing as markdown (passthrough with frontmatter)
 * @param {Object} briefing - Gemini briefing object
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - Markdown content
 */
function formatAnalysisLog(briefing, date) {
  const frontmatter = generateFrontmatter(date, 'analysis', ['github', 'gcp_logging', 'station_monitor', 'gemini']);

  // Briefing already contains markdown content
  let markdown = `${frontmatter}

# Glass Box Intelligence Briefing - ${date}

`;

  // Add briefing sections
  if (briefing.executive_summary && briefing.executive_summary.length > 0) {
    markdown += '## Executive Summary\n\n';
    for (const point of briefing.executive_summary) {
      markdown += `- ${point}\n`;
    }
    markdown += '\n';
  }

  if (briefing.repository_activity) {
    markdown += '## Repository Activity\n\n';
    markdown += briefing.repository_activity + '\n\n';
  }

  if (briefing.deployment_events) {
    markdown += '## Deployment Events\n\n';
    markdown += briefing.deployment_events + '\n\n';
  }

  if (briefing.development_activity) {
    markdown += '## Development Activity\n\n';
    markdown += briefing.development_activity + '\n\n';
  }

  if (briefing.context_checkpoints) {
    markdown += '## Context Checkpoints\n\n';
    markdown += briefing.context_checkpoints + '\n\n';
  }

  if (briefing.observations) {
    markdown += '## Curator Observations & Recommendations\n\n';
    markdown += briefing.observations + '\n\n';
  }

  markdown += `---

*Generated by Squeegee Intelligence System on ${briefing.generated_at || new Date().toISOString()}*\n`;

  return markdown;
}

/**
 * Get file path for log type
 * @param {string} logType - Type of log
 * @param {string} date - YYYY-MM-DD date string
 * @returns {string} - File path in repo
 */
function getLogFilePath(logType, date) {
  const dateObj = parseDate(date);
  const year = dateObj.getFullYear();
  const month = String(dateObj.getMonth() + 1).padStart(2, '0');

  const pathMap = {
    commits: `logs/commits/${year}/${month}/${date}.md`,
    prs: `logs/pull_requests/${year}/${month}/${date}.md`,
    pull_requests: `logs/pull_requests/${year}/${month}/${date}.md`,
    deployments: `logs/deployments/${year}/${month}/${date}.md`,
    agents: `logs/agents/${year}/${month}/${date}.md`,
    checkpoints: `logs/checkpoints/${year}/${month}/${date}.md`,
    analysis: `logs/analysis/${year}/${month}/${date}.md`
  };

  return pathMap[logType] || `logs/${logType}/${year}/${month}/${date}.md`;
}

/**
 * Write single log file to GitHub
 * @param {Octokit} octokit - GitHub API client
 * @param {string} owner - Repo owner
 * @param {string} repo - Repo name
 * @param {string} path - File path
 * @param {string} content - File content
 * @param {string} message - Commit message
 * @returns {Promise<Object>} - Write result
 */
async function writeLogFile(octokit, owner, repo, path, content, message) {
  try {
    // Check if file exists (get current SHA for update)
    let existingSha = null;
    try {
      const { data } = await octokit.repos.getContent({
        owner,
        repo,
        path
      });
      existingSha = data.sha;
    } catch (error) {
      // 404 means file doesn't exist, which is fine
      if (error.status !== 404) {
        throw error;
      }
    }

    // Create or update file
    const payload = {
      owner,
      repo,
      path,
      message,
      content: Buffer.from(content, 'utf-8').toString('base64'),
      committer: {
        name: 'squeegee-bot',
        email: 'squeegee@glassboxsolutions.com'
      },
      author: {
        name: 'squeegee-bot',
        email: 'squeegee@glassboxsolutions.com'
      }
    };

    if (existingSha) {
      payload.sha = existingSha;
    }

    const { data } = await octokit.repos.createOrUpdateFileContents(payload);

    return {
      success: true,
      file_path: path,
      commit_sha: data.commit.sha,
      commit_url: data.commit.html_url,
      error: null
    };
  } catch (error) {
    throw new GitHubAPIError(
      `Failed to write log file ${path}: ${error.message}`,
      error.status || 500,
      `PUT /repos/${owner}/${repo}/contents/${path}`
    );
  }
}

/**
 * Write intelligence data to logs
 * @param {Object} data - Collected intelligence data (from collectors)
 * @param {string} logType - Type of log ("commits" | "prs" | "agents" | "deployments" | "checkpoints" | "analysis")
 * @param {Date|string} date - Date of the data
 * @param {Object} config - Configuration object
 * @returns {Promise<Object>} - Log write result
 */
async function write(data, logType, date, config) {
  const githubToken = config.github_token;

  if (!githubToken) {
    throw new Error('GitHub token not configured');
  }

  // Parse date if string
  const dateStr = typeof date === 'string' ? date : formatDate(date);

  // Parse docs repo (format: owner/repo)
  const [owner, repo] = config.intelligence.docs_repo.split('/');

  console.log(`Writing ${logType} log for ${dateStr} to ${owner}/${repo}`);

  // Format content based on log type
  let content;
  switch (logType) {
    case 'commits':
      content = formatCommitsLog(data, dateStr);
      break;
    case 'prs':
      content = formatPRsLog(data, dateStr);
      break;
    case 'deployments':
      content = formatDeploymentsLog(data, dateStr);
      break;
    case 'agents':
      content = formatAgentsLog(data, dateStr);
      break;
    case 'checkpoints':
      content = formatCheckpointsLog(data, dateStr);
      break;
    case 'analysis':
      content = formatAnalysisLog(data, dateStr);
      break;
    default:
      throw new Error(`Unknown log type: ${logType}`);
  }

  // Get file path
  const filePath = getLogFilePath(logType, dateStr);
  const commitMessage = `chore: update ${logType} log for ${dateStr}`;

  // Write to GitHub with retry
  const octokit = createOctokit(githubToken);

  const result = await retryWithBackoff(
    () => writeLogFile(octokit, owner, repo, filePath, content, commitMessage),
    3,
    2000
  );

  console.log(`Successfully wrote ${logType} log:`, {
    file_path: result.file_path,
    commit_sha: result.commit_sha.substring(0, 7)
  });

  return result;
}

/**
 * Write all intelligence log types to GitHub in one call
 * @param {Object} intelligence - Collected intelligence data { github, gcp, station, checkpoints }
 * @param {Object} briefing - Gemini briefing object
 * @param {string} date - YYYY-MM-DD date string
 * @param {Object} config - Configuration object
 * @returns {Promise<Array>} - Array of write results
 */
async function writeAll(intelligence, briefing, date, config) {
  const results = [];

  results.push(await write(intelligence.github, 'commits', date, config));
  results.push(await write(intelligence.github, 'prs', date, config));
  results.push(await write(intelligence.gcp, 'deployments', date, config));
  results.push(await write(intelligence.station, 'agents', date, config));
  results.push(await write(intelligence.checkpoints || [], 'checkpoints', date, config));
  results.push(await write(briefing, 'analysis', date, config));

  return results;
}

module.exports = {
  write,
  writeAll,
  // Export for testing
  generateFrontmatter,
  formatCommitsLog,
  formatPRsLog,
  formatDeploymentsLog,
  formatAgentsLog,
  formatCheckpointsLog,
  formatAnalysisLog,
  getLogFilePath
};
