"""The golden-corpus gate, and the reasons to believe it.

``tools/golden_gate.py`` is the first guard in this package that watches output
across *time* rather than within a run. The existing determinism suites generate
the same spec twice and compare the two — which proves the machinery has no leak
today, and says nothing about whether today still matches last month. This gate
answers that, so it is worth being precise about what it can and cannot see.

The contract is **all generated bytes, except checkout-dependent provenance**,
and most of this file exists to keep each half of that sentence honest:

* the gate reads the **bytes**, not the corpus's report about its own bytes — a
  document mutated without touching its manifest, a declared document deleted,
  and a stray file nobody declared are each caught by their own probe, because
  each one used to pass;
* the exemption list is **exactly** ``{substrateSha}`` and a test fails if it
  grows, because every name added there is a field the gate stops watching and
  the cost of that is invisible;
* a version bump **does** redden the gate, which is the reviewable moment a
  release should have;
* the digest is **faithful** — it stands in for the file's own bytes, checked by
  round-tripping every real manifest the demo caseload produced;
* the redaction paths are **checked, not assumed** — a manifest that stops
  carrying ``provenance.substrateSha`` makes the tool raise rather than quietly
  digest a different shape and report clean;
* ``--record`` cannot bless a run it has not proved reproducible, and cannot be
  fired without saying what it meant to accept.

That last cluster is the failure mode this file exists for. A gate that silently
measures the wrong thing and passes is worse than no gate, because it also
retires the suspicion that would have found the drift.

@Developed & Documented by Glass Box Solutions, Inc. using human ingenuity and modern technology
"""

from __future__ import annotations

import copy
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest
import yaml

from conftest import requires_substrate

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))

import golden_gate
from golden_gate import (
    AXES,
    CASE_REDACTIONS,
    CI_TIER,
    CORPORA,
    EXAMPLES,
    GOLDEN_FORMAT,
    PACKAGE,
    REDACTED_KEYS,
    SUITE_TIER,
    Corpus,
    GoldenError,
    canonical_json_bytes,
    compare,
    digest_corpus,
    documents_digest,
    file_digests,
    normalized_manifest_digest,
)

TOOL = PACKAGE / "tools" / "golden_gate.py"

SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
"""What every digest in a golden has to look like."""


def _demo_manifest_paths(demo_caseload: Path) -> list[Path]:
    """Every case manifest of the shared demo caseload."""
    return sorted(demo_caseload.glob("*/manifest.json"))


def _write_json(path: Path, payload: Any) -> Path:
    """Write *payload* the way the engine writes a manifest."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_json_bytes(payload))
    return path


def _build_corpus(root: Path, documents: tuple[str, ...] = ("001.pdf", "002.pdf")) -> Path:
    """A minimal but structurally real output tree, with no substrate needed.

    Everything the byte-level probes need and nothing they do not: one case,
    a manifest declaring its documents, the two per-case artifacts, and files
    on disk. Built by hand rather than generated so a probe can corrupt exactly
    one thing and leave the rest correct — which is what makes the result a
    statement about that one thing.
    """
    root.mkdir(parents=True, exist_ok=True)
    provenance = {
        "zeroRealPii": True,
        "generator": "wc-synthetic-caseload-engine@0.9.0",
        "substrateSha": "a" * 40,
    }
    _write_json(
        root / "caseload_manifest.json",
        {"caseloadId": "probe", "generator": "wc@0.9.0", "provenance": dict(provenance)},
    )
    case = root / "case-a"
    (case / "documents").mkdir(parents=True, exist_ok=True)
    for index, name in enumerate(documents):
        (case / "documents" / name).write_bytes(f"body of {name}".encode())
        del index
    _write_json(
        case / "manifest.json",
        {
            "caseId": "case-a",
            "documents": [
                {"filename": name, "subtype": "MEDICAL_REPORT", "md5Checksum": f"{index:032d}"}
                for index, name in enumerate(documents)
            ],
            "provenance": dict(provenance),
        },
    )
    (case / "seed.yaml").write_text("case_id: case-a\n", encoding="utf-8")
    (case / "case_facts.yaml").write_text("surgery:\n  status: none\n", encoding="utf-8")
    return root


# ---------------------------------------------------------------------------
# The registry covers what is shipped
# ---------------------------------------------------------------------------


def test_every_shipped_example_spec_is_a_registered_corpus() -> None:
    """A new ``examples/*.yaml`` is gated, or this test says so.

    The gate is only as wide as its registry, and a registry maintained by
    memory is a registry that drifts. Adding a showcase without a golden should
    cost one second of test time to discover, not one release.
    """
    on_disk = {path.stem for path in EXAMPLES.glob("*.yaml")}
    registered = {corpus.name for corpus in CORPORA}
    assert on_disk == registered, (
        f"examples/ and CORPORA disagree — unregistered: {sorted(on_disk - registered)}, "
        f"registered but absent: {sorted(registered - on_disk)}"
    )


def test_every_registered_corpus_is_in_exactly_one_tier() -> None:
    """Every corpus is gated once: by the suite or by the CI step, never neither."""
    for corpus in CORPORA:
        assert corpus.tier in (SUITE_TIER, CI_TIER), f"{corpus.name}: tier {corpus.tier!r}"
    tiers = {corpus.tier for corpus in CORPORA}
    assert tiers == {SUITE_TIER, CI_TIER}, (
        "both tiers must be populated — an empty tier means one of the two gates "
        f"runs nothing, and the tiers present are {sorted(tiers)}"
    )


def test_medical_story_showcase_is_registered_as_suite_tier() -> None:
    """AJC-62 R73: the new feature-on corpus has one exact registry row."""
    rows = [corpus for corpus in CORPORA if corpus.name == "medical-story-showcase"]
    assert len(rows) == 1
    corpus = rows[0]
    assert corpus.tier == SUITE_TIER
    assert corpus.spec == EXAMPLES / "medical-story-showcase.yaml"
    assert corpus.golden == PACKAGE / "tests" / "golden" / "medical-story-showcase.json"


def test_medical_story_showcase_golden_has_exact_five_cases_and_seeds() -> None:
    """AJC-62 R77 step 14: the recording and source name the same five seeds."""
    expected_order = (
        ("flagship-nonindustrial-cancer-noise-a", 622001),
        ("flagship-nonindustrial-cancer-noise-b", 622002),
        ("flagship-nonindustrial-cancer-noise-c", 622003),
        ("lc4664-prior-award-overlap", 622004),
        ("diabetic-neuropathy-cts-confound", 622005),
    )
    expected = {
        "flagship-nonindustrial-cancer-noise-a": 622001,
        "flagship-nonindustrial-cancer-noise-b": 622002,
        "flagship-nonindustrial-cancer-noise-c": 622003,
        "lc4664-prior-award-overlap": 622004,
        "diabetic-neuropathy-cts-confound": 622005,
    }
    spec = yaml.safe_load((EXAMPLES / "medical-story-showcase.yaml").read_text())
    assert tuple((case["case_id"], case["rng_seed"]) for case in spec["cases"]) == (
        expected_order
    )
    assert {case["case_id"]: case["rng_seed"] for case in spec["cases"]} == expected

    golden_path = PACKAGE / "tests" / "golden" / "medical-story-showcase.json"
    assert golden_path.is_file(), (
        "the Step-14 semantic artifacts are ready, but the orchestrator has not "
        "recorded tests/golden/medical-story-showcase.json yet"
    )
    golden = json.loads(golden_path.read_text(encoding="utf-8"))
    assert golden["corpus"] == "medical-story-showcase"
    assert golden["tier"] == SUITE_TIER
    assert set(golden["cases"]) == set(expected)
    assert golden["caseCount"] == 5


def test_every_registered_corpus_has_a_well_formed_golden() -> None:
    """The goldens are committed, current-format, and internally consistent.

    The old count was right to be strict but wrong to assume the tree had one
    non-case file. Recording that part of the tree keeps the equality strict
    while making its shape checked data rather than an embedded assumption.
    """
    for corpus in CORPORA:
        assert corpus.golden.is_file(), (
            f"{corpus.name}: no committed golden. Record one with "
            f"`python tools/golden_gate.py --record --only {corpus.name}`"
        )
        golden = json.loads(corpus.golden.read_text(encoding="utf-8"))
        assert golden["format"] == GOLDEN_FORMAT
        assert golden["corpus"] == corpus.name
        assert golden["tier"] == corpus.tier
        assert golden["spec"] == corpus.spec.relative_to(PACKAGE).as_posix()

        cases = golden["cases"]
        assert cases, f"{corpus.name}: golden records no cases"
        assert golden["caseCount"] == len(cases)
        assert golden["documentCount"] == sum(case["documentCount"] for case in cases.values())
        assert golden["fileCount"] == sum(
            case["fileCount"] for case in cases.values()
        ) + len(golden["rootFiles"])
        assert "caseload_manifest.json" in golden["rootFiles"]
        assert golden["rootFiles"] == sorted(golden["rootFiles"])
        assert SHA256_RE.match(golden["caseload"])
        assert SHA256_RE.match(golden["corpusTree"])
        for case_id, case in cases.items():
            for axis, _label in AXES:
                assert SHA256_RE.match(case[axis]), f"{corpus.name}/{case_id}: bad {axis} digest"
            assert case["documentCount"] > 0
            assert 0 < case["distinctSubtypes"] <= case["documentCount"]
            # seed.yaml + case_facts.yaml + manifest.json + every document.
            assert case["fileCount"] == case["documentCount"] + 3


def test_truth_subtree_accounting_is_complete_when_present() -> None:
    """A recorded truth subtree contains its index and one file per case.

    Strictness was never the defect in the old one-root-file invariant; its
    assumed tree shape was. Once truth files are present, their exact recorded
    names make a missing case manifest or an unowned extra artifact fail loud.
    """
    for corpus in CORPORA:
        golden = json.loads(corpus.golden.read_text(encoding="utf-8"))
        truth_files = [name for name in golden["rootFiles"] if name.startswith("truth/")]
        if truth_files:
            expected = [
                *(f"truth/{case_id}.truth.json" for case_id in golden["cases"]),
                "truth/caseload.truth.json",
            ]
            assert truth_files == sorted(expected)


def test_a_golden_records_the_provenance_needed_to_explain_a_drift() -> None:
    """The recording environment is captured, or a red gate cannot be diagnosed."""
    for corpus in CORPORA:
        recorded = json.loads(corpus.golden.read_text(encoding="utf-8"))["recordedWith"]
        assert recorded["engine"]
        assert recorded["python"]
        # The versions that actually decide rendered bytes. ReportLab lays the
        # PDFs out; when a corpus drifts for no reason in the diff, this is
        # usually where the reason is.
        assert recorded["dependencies"]["reportlab"] != "not-installed"
        # And the font the substrate's scan simulator rasterizes its fax header
        # with. It falls back to PIL's default *silently* when the DejaVu
        # package is absent, which substitutes different pixels into every
        # scanned PDF and would otherwise be an unexplainable golden failure.
        assert recorded["systemFonts"], "no system-font provenance recorded"


# ---------------------------------------------------------------------------
# The frozen AJC-62 pre-M3 baseline
# ---------------------------------------------------------------------------

AJC62_GOLDEN_CONTRACT = Path(__file__).resolve().parent / "fixtures" / (
    "ajc62_pre_m3_golden_contract.json"
)
"""R67/R73: raw hashes of the three no-re-record goldens at eedad1093, plus the
complete pre-M3 ``doctrine-showcase`` payload for step 13's addition-only proof."""


def test_pre_m3_unchanged_corpus_golden_files_match_the_frozen_ajc62_baseline() -> None:
    """AJC-62 R73: three corpora receive no re-record — not even a deliberate one.

    The ordinary golden gate compares fresh generation against the committed
    golden, so it goes green again the moment somebody re-records — which is
    exactly the move this baseline exists to forbid for ``demo-caseload``,
    ``money-showcase`` and ``personas-showcase`` during AJC-62. The comparison
    is the raw SHA-256 of the committed golden files' own bytes against the
    frozen fixture, so a re-record cannot ride through on a green ``--check``:
    the file moved, and this says so regardless of what generated it.

    ``doctrine-showcase`` is deliberately absent from the hash set — R73 grants
    it exactly one addition-only re-record at build step 13, proved by its own
    test against the complete payload this same fixture embeds.
    """
    contract = json.loads(AJC62_GOLDEN_CONTRACT.read_text(encoding="utf-8"))
    frozen = contract["golden_sha256"]
    assert set(frozen) == {"demo-caseload", "money-showcase", "personas-showcase"}, (
        "the frozen contract must cover exactly the three no-re-record corpora"
    )

    golden_dir = Path(__file__).resolve().parent / "golden"
    drifted: list[str] = []
    for name, expected in sorted(frozen.items()):
        actual = hashlib.sha256((golden_dir / f"{name}.json").read_bytes()).hexdigest()
        if actual != expected:
            drifted.append(f"{name}: recorded {expected}, committed file is {actual}")
    assert not drifted, (
        "a golden AJC-62 froze byte-identical has been rewritten — no build step "
        "may re-record these corpora, deliberately or otherwise:\n  "
        + "\n  ".join(drifted)
    )

    # The step-13 consumer's payload rides in the same fixture; a light shape
    # guard keeps it from being mangled before that step needs it.
    doctrine = contract["doctrine_showcase_pre_m3"]
    assert doctrine["corpus"] == "doctrine-showcase"
    assert doctrine["cases"], "the embedded pre-M3 doctrine payload lost its cases"


def test_doctrine_showcase_rerecord_is_addition_only_for_preexisting_cases() -> None:
    """AJC-62 R73: the one doctrine re-record adds one case and changes no old case.

    The expected side is the complete pre-M3 payload captured before M3. It is
    deliberately not derived from the current golden: comparing the re-record
    with itself would be the oracle-integrity doctrine's forbidden Form A.
    """
    contract = json.loads(AJC62_GOLDEN_CONTRACT.read_text(encoding="utf-8"))
    before = contract["doctrine_showcase_pre_m3"]
    golden = Path(__file__).resolve().parent / "golden" / "doctrine-showcase.json"
    after = json.loads(golden.read_text(encoding="utf-8"))

    preexisting_cases = {
        "showcase-death-dependency",
        "showcase-firefighter-presumption",
        "showcase-imr-challenge",
        "showcase-psychiatric",
        "showcase-rating-doctrines",
        "showcase-threshold-defences",
    }
    added_cases = {"showcase-hikida-justice"}
    assert set(before["cases"]) == preexisting_cases
    assert set(after["cases"]) == preexisting_cases | added_cases
    assert set(after["cases"]) - set(before["cases"]) == added_cases

    case_keys = {
        "documentCount",
        "distinctSubtypes",
        "fileCount",
        "tree",
        "documents",
        "manifest",
        "seed",
        "facts",
    }

    def canonical_json(value: Any) -> bytes:
        return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")

    changed_preexisting: list[str] = []
    for case_id in sorted(preexisting_cases):
        assert set(before["cases"][case_id]) == case_keys
        assert set(after["cases"][case_id]) == case_keys
        if canonical_json(after["cases"][case_id]) != canonical_json(
            before["cases"][case_id]
        ):
            changed_preexisting.append(case_id)
    assert not changed_preexisting, (
        "the doctrine re-record changed pre-existing case dictionaries: "
        f"{changed_preexisting}"
    )

    allowed_top_level_changes = {
        "cases",
        "caseCount",
        "documentCount",
        "fileCount",
        "rootFiles",
        "caseload",
        "corpusTree",
    }
    assert set(after) == set(before)
    assert allowed_top_level_changes < set(before)
    stable_top_level = set(before) - allowed_top_level_changes
    assert canonical_json({key: after[key] for key in stable_top_level}) == canonical_json(
        {key: before[key] for key in stable_top_level}
    )

    new_truth_file = "truth/showcase-hikida-justice.truth.json"
    assert set(after["rootFiles"]) - set(before["rootFiles"]) == {new_truth_file}
    assert set(before["rootFiles"]) - set(after["rootFiles"]) == set()
    assert after["rootFiles"] == sorted(after["rootFiles"])

    final_cases = after["cases"]
    assert after["caseCount"] == len(final_cases)
    assert after["documentCount"] == sum(
        case["documentCount"] for case in final_cases.values()
    )
    assert after["fileCount"] == len(after["rootFiles"]) + sum(
        case["fileCount"] for case in final_cases.values()
    )


# ---------------------------------------------------------------------------
# The exemption list
# ---------------------------------------------------------------------------


def test_exactly_one_field_is_exempt_from_the_digest() -> None:
    """The redaction list is the one thing here that can only weaken the gate.

    Every name in it is a field the gate stops watching, and the cost is
    invisible: it keeps reporting clean, just about less. Pinning the set means
    widening it is a decision somebody has to argue for in a diff rather than a
    line that slips through review.

    ``substrateSha`` earns its place by describing the *checkout* rather than
    the corpus — it disagrees with ``substrate_pin.txt`` in a clean tree — so
    digesting it would fail every commit for a reason unrelated to the bytes.
    """
    assert frozenset({"substrateSha"}) == REDACTED_KEYS
    for redactions in (
        golden_gate.CASE_REDACTIONS,
        golden_gate.CASELOAD_REDACTIONS,
    ):
        for path in redactions:
            assert path[-1] in REDACTED_KEYS, f"{path} redacts a field not in REDACTED_KEYS"


# ---------------------------------------------------------------------------
# The digest is faithful
# ---------------------------------------------------------------------------


@requires_substrate
def test_the_normalizer_reproduces_every_demo_manifest_byte_for_byte(
    demo_caseload: Path,
) -> None:
    """A digest may only stand in for a file it can reproduce.

    The tool digests a *parsed and re-serialized* manifest so it can neutralize
    one volatile field. That is only honest if the round trip is lossless — a
    reformatted float or a mangled character would mean the digest describes
    something the file is not. Checked against every manifest the demo caseload
    actually produces rather than a constructed sample.
    """
    paths = _demo_manifest_paths(demo_caseload)
    assert paths, "the demo caseload produced no manifests"
    for path in paths:
        raw = path.read_bytes()
        assert canonical_json_bytes(json.loads(raw)) == raw, f"{path}: round trip is lossy"


def test_a_manifest_the_normalizer_cannot_reproduce_is_refused(tmp_path: Path) -> None:
    """Compact JSON is not what the engine writes, so it is not silently digested."""
    path = tmp_path / "manifest.json"
    path.write_text(json.dumps({"provenance": {"generator": "x", "substrateSha": "y"}}))
    with pytest.raises(GoldenError, match="byte-for-byte"):
        normalized_manifest_digest(path, CASE_REDACTIONS)


# ---------------------------------------------------------------------------
# The gate reads bytes, not the corpus's report about its bytes
# ---------------------------------------------------------------------------


def test_a_document_mutated_without_touching_its_manifest_is_caught(tmp_path: Path) -> None:
    """The defect the first version of this tool would have shipped past.

    Hashing the manifest's *declared* MD5s means trusting the corpus's report
    about itself. A renderer that writes different bytes while its bookkeeping
    stays stale produces exactly this: identical manifest, different file. The
    tree digest moves, the declared-checksum digest does not, and the pair of
    them says which half broke.
    """
    root = _build_corpus(tmp_path / "corpus")
    before = digest_corpus(root)

    (root / "case-a" / "documents" / "001.pdf").write_bytes(b"different bytes entirely")
    after = digest_corpus(root)

    assert after["cases"]["case-a"]["tree"] != before["cases"]["case-a"]["tree"], (
        "a rendered document changed on disk and the gate did not notice"
    )
    assert after["corpusTree"] != before["corpusTree"]
    # And the tell: the manifest's own account of the file is unchanged, which
    # is precisely why hashing only that account was not enough.
    assert after["cases"]["case-a"]["documents"] == before["cases"]["case-a"]["documents"]
    assert after["cases"]["case-a"]["manifest"] == before["cases"]["case-a"]["manifest"]

    problems = compare(CORPORA[0], before, after)
    assert any("file bytes" in problem for problem in problems), problems


def test_a_declared_document_missing_from_disk_is_rejected(tmp_path: Path) -> None:
    """A manifest describing a corpus that is not there is not a corpus."""
    root = _build_corpus(tmp_path / "corpus")
    (root / "case-a" / "documents" / "002.pdf").unlink()
    with pytest.raises(GoldenError, match="not in documents/"):
        digest_corpus(root)


def test_an_undeclared_file_in_the_tree_is_rejected(tmp_path: Path) -> None:
    """A stray artifact is drift even though no manifest mentions it.

    This is the direction a manifest can never catch, because the manifest is
    what it is measured against. A temp file, a new sidecar, or the
    ``__pycache__`` that determinism rule 5 exists to prevent would all have
    ridden along invisibly.
    """
    root = _build_corpus(tmp_path / "corpus")
    (root / "case-a" / "documents" / "stray.pdf").write_bytes(b"nobody declared me")
    with pytest.raises(GoldenError, match="no manifest entry declares"):
        digest_corpus(root)


def test_a_stray_file_outside_documents_still_moves_the_tree_digest(tmp_path: Path) -> None:
    """Coverage is the whole tree, not only the documents folder."""
    root = _build_corpus(tmp_path / "corpus")
    before = digest_corpus(root)
    (root / "case-a" / "notes.txt").write_text("left behind", encoding="utf-8")
    after = digest_corpus(root)
    assert after["cases"]["case-a"]["tree"] != before["cases"]["case-a"]["tree"]
    assert after["cases"]["case-a"]["fileCount"] == before["cases"]["case-a"]["fileCount"] + 1


def test_every_file_in_the_tree_is_accounted_for(tmp_path: Path) -> None:
    """Nothing is excluded — the two manifests are normalized, not skipped."""
    root = _build_corpus(tmp_path / "corpus")
    digests = file_digests(root)
    assert set(digests) == {
        "caseload_manifest.json",
        "case-a/manifest.json",
        "case-a/seed.yaml",
        "case-a/case_facts.yaml",
        "case-a/documents/001.pdf",
        "case-a/documents/002.pdf",
    }


def test_the_tree_digest_ignores_substrate_sha_and_nothing_else(tmp_path: Path) -> None:
    """The exemption applies through the tree digest too, and stops there."""
    root = _build_corpus(tmp_path / "corpus")
    baseline = digest_corpus(root)

    manifest_path = root / "case-a" / "manifest.json"
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    payload["provenance"]["substrateSha"] = "f" * 40
    _write_json(manifest_path, payload)
    assert digest_corpus(root)["corpusTree"] == baseline["corpusTree"], (
        "substrateSha is checkout-dependent and must not read as corpus drift"
    )

    payload["provenance"]["generator"] = "wc-synthetic-caseload-engine@99.0.0"
    _write_json(manifest_path, payload)
    assert digest_corpus(root)["corpusTree"] != baseline["corpusTree"], (
        "a version bump changes shipped bytes and must redden the gate"
    )


# ---------------------------------------------------------------------------
# The digest is sensitive to content, and to the version
# ---------------------------------------------------------------------------


@requires_substrate
def test_the_digest_notices_content_and_the_engine_version(
    demo_caseload: Path, tmp_path: Path
) -> None:
    """A version bump is a release event, and the gate treats it as one.

    An earlier cut of this tool redacted ``provenance.generator`` so a bump
    would stay green. That inverted the contract: the generator string is part
    of every manifest's bytes, so a bump genuinely changes shipped output, and
    a gate that hides it is a gate that lets a release through unexamined.
    """
    source = _demo_manifest_paths(demo_caseload)[0]
    baseline = normalized_manifest_digest(source, CASE_REDACTIONS)
    payload = json.loads(source.read_text(encoding="utf-8"))

    moved_sha = copy.deepcopy(payload)
    moved_sha["provenance"]["substrateSha"] = "0" * 40
    assert (
        normalized_manifest_digest(
            _write_json(tmp_path / "sha.json", moved_sha), CASE_REDACTIONS
        )
        == baseline
    ), "a substrate-SHA change describes the checkout, not the corpus"

    moved_version = copy.deepcopy(payload)
    moved_version["provenance"]["generator"] = "wc-synthetic-caseload-engine@99.0.0"
    assert (
        normalized_manifest_digest(
            _write_json(tmp_path / "version.json", moved_version), CASE_REDACTIONS
        )
        != baseline
    ), "a version bump changes shipped bytes and must redden the gate"

    moved_checksum = copy.deepcopy(payload)
    moved_checksum["documents"][0]["md5Checksum"] = "0" * 32
    assert (
        normalized_manifest_digest(
            _write_json(tmp_path / "checksum.json", moved_checksum), CASE_REDACTIONS
        )
        != baseline
    ), "a moved document checksum must read as corpus drift"

    moved_ledger = copy.deepcopy(payload)
    moved_ledger["caseFacts"]["treatment"]["status"] = "probe-value"
    assert (
        normalized_manifest_digest(
            _write_json(tmp_path / "ledger.json", moved_ledger), CASE_REDACTIONS
        )
        != baseline
    ), "a moved ledger fact must read as corpus drift"


@requires_substrate
def test_a_stale_redaction_path_raises_instead_of_digesting_a_different_shape(
    demo_caseload: Path, tmp_path: Path
) -> None:
    """The redaction paths are checked against the manifest, not assumed.

    If ``provenance.substrateSha`` is ever renamed or dropped, this tool would
    go on digesting happily — and would then be digesting the *unredacted*
    provenance, which moves per checkout, so the gate would fail everywhere for
    a reason nobody could read. Raising is the only outcome that leads anywhere.
    """
    payload = json.loads(_demo_manifest_paths(demo_caseload)[0].read_text(encoding="utf-8"))
    del payload["provenance"]["substrateSha"]
    path = _write_json(tmp_path / "manifest.json", payload)
    with pytest.raises(GoldenError, match="substrateSha"):
        normalized_manifest_digest(path, CASE_REDACTIONS)


@requires_substrate
def test_the_documents_digest_moves_with_content_and_with_order(
    demo_caseload: Path,
) -> None:
    """Both are real drift: a changed file, and the same files in a new order."""
    manifest = json.loads(_demo_manifest_paths(demo_caseload)[0].read_text(encoding="utf-8"))
    documents = manifest["documents"]
    baseline = documents_digest(documents, "probe")

    changed = copy.deepcopy(documents)
    changed[0]["md5Checksum"] = "0" * 32
    assert documents_digest(changed, "probe") != baseline

    renamed = copy.deepcopy(documents)
    renamed[0]["filename"] = "renamed.pdf"
    assert documents_digest(renamed, "probe") != baseline

    assert documents_digest(list(reversed(documents)), "probe") != baseline

    dropped = copy.deepcopy(documents)[:-1]
    assert documents_digest(dropped, "probe") != baseline


def test_a_document_entry_without_a_checksum_is_an_error() -> None:
    """A manifest that cannot supply the pair is not silently digested as empty."""
    with pytest.raises(GoldenError, match="filename/md5Checksum"):
        documents_digest([{"filename": "a.pdf"}], "probe")


# ---------------------------------------------------------------------------
# The report says what drifted
# ---------------------------------------------------------------------------


def _golden_stub(**cases: dict[str, Any]) -> dict[str, Any]:
    """A minimal golden payload for exercising :func:`compare`."""
    return {
        "caseCount": len(cases),
        "documentCount": sum(case["documentCount"] for case in cases.values()),
        "fileCount": sum(case["fileCount"] for case in cases.values()),
        "corpusTree": "c" * 64,
        "caseload": "l" * 64,
        "cases": cases,
    }


def _case_stub(**overrides: Any) -> dict[str, Any]:
    """One recorded case, every axis present."""
    case: dict[str, Any] = {
        "documentCount": 3,
        "distinctSubtypes": 2,
        "fileCount": 6,
        "tree": "t" * 64,
        "documents": "d" * 64,
        "manifest": "m" * 64,
        "seed": "s" * 64,
        "facts": "f" * 64,
    }
    case.update(overrides)
    return case


def test_the_report_names_the_axis_that_drifted() -> None:
    """"Something changed" is not a finding; "the seed changed" is."""
    corpus = CORPORA[0]
    golden = _golden_stub(alpha=_case_stub())
    for axis, label in AXES:
        fresh = _golden_stub(alpha=_case_stub(**{axis: "9" * 64}))
        problems = compare(corpus, golden, fresh)
        assert any(label in problem and "alpha" in problem for problem in problems), (
            f"a drifted {axis} digest was not reported as {label!r}: {problems}"
        )


def test_the_report_names_added_and_missing_cases() -> None:
    """A corpus that gained or lost a case is a shape change, reported as one."""
    corpus = CORPORA[0]
    golden = _golden_stub(alpha=_case_stub())
    fresh = _golden_stub(beta=_case_stub())
    problems = compare(corpus, golden, fresh)
    assert any("alpha" in problem and "did not produce" in problem for problem in problems)
    assert any("beta" in problem and "absent from the golden" in problem for problem in problems)


def test_the_report_names_a_changed_document_count_in_plain_numbers() -> None:
    """A count is a diagnosis; a digest is only a symptom."""
    corpus = CORPORA[0]
    golden = _golden_stub(alpha=_case_stub())
    fresh = _golden_stub(alpha=_case_stub(documentCount=4, documents="9" * 64))
    problems = compare(corpus, golden, fresh)
    assert any("documents 3 recorded, 4 now" in problem for problem in problems)


def test_an_identical_pair_reports_nothing() -> None:
    """The gate has to be able to say yes, or it is not a gate."""
    golden = _golden_stub(alpha=_case_stub())
    assert compare(CORPORA[0], golden, copy.deepcopy(golden)) == []


# ---------------------------------------------------------------------------
# --record cannot bless what it has not proved
# ---------------------------------------------------------------------------


def test_record_refuses_a_corpus_whose_two_runs_disagree(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Recording a single run asserts reproducibility without testing it.

    Worse than useless: if the corpus really had become nondeterministic, that
    single run is how the nondeterminism gets pinned as the baseline, and every
    later ``--check`` fails for a reason the recording caused.
    """
    golden_path = tmp_path / "probe.json"
    golden_path.write_text('{"format": 1, "sentinel": "untouched"}\n', encoding="utf-8")
    corpus = Corpus(name="probe", tier=SUITE_TIER, why="probe")
    monkeypatch.setattr(Corpus, "golden", property(lambda self: golden_path))

    runs = iter(("first", "second"))

    def _alternating(_corpus: Corpus, out_dir: Path) -> None:
        _build_corpus(out_dir)
        (out_dir / "case-a" / "documents" / "001.pdf").write_bytes(next(runs).encode())

    monkeypatch.setattr(golden_gate, "generate_corpus", _alternating)
    monkeypatch.setattr(golden_gate, "validate_corpus", lambda *_args: None)

    assert golden_gate.record([corpus]) == 1
    assert "untouched" in golden_path.read_text(encoding="utf-8"), (
        "a golden was written from a run that was never proved reproducible"
    )


def test_record_leaves_earlier_goldens_untouched_when_a_later_corpus_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """All-or-nothing. A half-recorded set is the worst artifact available.

    Half the goldens refreshed against new code and half still describing the
    old, with a ``git status`` that looks like a deliberate subset — a reviewer
    has no way to see that the set is incoherent.
    """
    goldens = {
        "good": tmp_path / "good.json",
        "bad": tmp_path / "bad.json",
    }
    for path in goldens.values():
        path.write_text('{"format": 1, "sentinel": "untouched"}\n', encoding="utf-8")
    monkeypatch.setattr(Corpus, "golden", property(lambda self: goldens[self.name]))

    def _generate(corpus: Corpus, out_dir: Path) -> None:
        if corpus.name == "bad":
            raise GoldenError("probe: generation failed")
        _build_corpus(out_dir)

    monkeypatch.setattr(golden_gate, "generate_corpus", _generate)
    monkeypatch.setattr(golden_gate, "validate_corpus", lambda *_args: None)

    corpora = [
        Corpus(name="good", tier=SUITE_TIER, why="probe"),
        Corpus(name="bad", tier=SUITE_TIER, why="probe"),
    ]
    assert golden_gate.record(corpora) == 1
    for name, path in goldens.items():
        assert "untouched" in path.read_text(encoding="utf-8"), (
            f"{name}.json was rewritten even though the record run failed"
        )


def test_record_records_when_both_runs_agree(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The happy path still works — a gate that only refuses is not a gate."""
    golden_path = tmp_path / "probe.json"
    monkeypatch.setattr(Corpus, "golden", property(lambda self: golden_path))
    monkeypatch.setattr(
        golden_gate, "generate_corpus", lambda _corpus, out_dir: _build_corpus(out_dir)
    )
    monkeypatch.setattr(golden_gate, "validate_corpus", lambda *_args: None)

    corpus = Corpus(name="probe", tier=SUITE_TIER, why="probe")
    assert golden_gate.record([corpus]) == 0
    written = json.loads(golden_path.read_text(encoding="utf-8"))
    assert written["caseCount"] == 1
    assert written["fileCount"] == 6
    assert written["rootFiles"] == ["caseload_manifest.json"]
    assert SHA256_RE.match(written["corpusTree"])


def test_a_failure_midway_through_writing_rolls_every_golden_back(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The generation phase is atomic; so is the write phase.

    Proving all the corpora reproducible before writing any of them closes the
    big window, and leaves a small one: the writes themselves. A full disk, a
    permissions change or a Ctrl-C between the first file and the second leaves
    exactly the incoherent set the design argues against, and no amount of
    care in the phase before it helps.

    The probe fails the *second* of two replacements, which is the only
    arrangement that can tell a real rollback from a lucky ordering: the first
    file has genuinely been replaced by the time the failure lands, so it can
    only be byte-identical again if something put it back.
    """
    goldens = {"first": tmp_path / "first.json", "second": tmp_path / "second.json"}
    for path in goldens.values():
        path.write_text('{"format": 1, "sentinel": "original"}\n', encoding="utf-8")
    before = {name: path.read_bytes() for name, path in goldens.items()}
    monkeypatch.setattr(Corpus, "golden", property(lambda self: goldens[self.name]))
    monkeypatch.setattr(
        golden_gate, "generate_corpus", lambda _corpus, out_dir: _build_corpus(out_dir)
    )
    monkeypatch.setattr(golden_gate, "validate_corpus", lambda *_args: None)

    real_replace = golden_gate.os.replace
    calls = {"n": 0}

    def _failing_replace(source: Any, destination: Any) -> None:
        calls["n"] += 1
        if calls["n"] == 2:
            raise OSError(28, "No space left on device", str(destination))
        return real_replace(source, destination)

    monkeypatch.setattr(golden_gate.os, "replace", _failing_replace)

    corpora = [
        Corpus(name="first", tier=SUITE_TIER, why="probe"),
        Corpus(name="second", tier=SUITE_TIER, why="probe"),
    ]
    assert golden_gate.record(corpora) == 1
    # At least the two commits; the rollback restores through os.replace as well.
    assert calls["n"] >= 2, "the probe never reached the second replacement"
    for name, path in goldens.items():
        assert path.read_bytes() == before[name], (
            f"{name}.json was left rewritten after the record run failed"
        )
    assert not list(tmp_path.glob(".*")), "a staged temporary was left behind"


def _two_corpus_record_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[list[Corpus], dict[str, Path], dict[str, bytes]]:
    """Two recordable corpora with committed goldens, and their original bytes."""
    goldens = {"first": tmp_path / "first.json", "second": tmp_path / "second.json"}
    for path in goldens.values():
        path.write_text('{"format": 1, "sentinel": "original"}\n', encoding="utf-8")
    before = {name: path.read_bytes() for name, path in goldens.items()}
    monkeypatch.setattr(Corpus, "golden", property(lambda self: goldens[self.name]))
    monkeypatch.setattr(
        golden_gate, "generate_corpus", lambda _corpus, out_dir: _build_corpus(out_dir)
    )
    monkeypatch.setattr(golden_gate, "validate_corpus", lambda *_args: None)
    corpora = [
        Corpus(name="first", tier=SUITE_TIER, why="probe"),
        Corpus(name="second", tier=SUITE_TIER, why="probe"),
    ]
    return corpora, goldens, before


def _replace_failing_on(
    calls: dict[str, int],
    failures: dict[int, BaseException],
    perform_first: frozenset[int] = frozenset(),
) -> Any:
    """An ``os.replace`` that raises on the numbered calls in *failures*.

    A call listed in *perform_first* does the real replacement and *then*
    raises, which is how an interrupt arriving between a successful replace and
    the next instruction is reproduced. That distinction is the whole content of
    the pre-tracking probe below: a failure before the replace and a failure
    after it leave the filesystem in two different states.
    """
    real_replace = golden_gate.os.replace

    def _replace(source: Any, destination: Any) -> None:
        calls["n"] += 1
        failure = failures.get(calls["n"])
        if failure is not None:
            if calls["n"] in perform_first:
                real_replace(source, destination)
            raise failure
        return real_replace(source, destination)

    return _replace


def test_an_interrupt_midway_through_writing_rolls_back_and_still_stops_the_program(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Ctrl-C is the interruption this function most needs to survive.

    An earlier version caught ``OSError`` and promised Ctrl-C recovery in its
    own docstring. ``KeyboardInterrupt`` inherits from ``BaseException``, not
    ``Exception``, so it matched nothing: an interrupt after the first
    replacement skipped the staged-file cleanup *and* the rollback, and left
    exactly the half-updated set the docstring said it prevented. The handler
    documenting a guarantee it does not implement is worse than no guarantee,
    because it is the reason nobody checks.

    Both halves are asserted, because either alone is satisfiable by a wrong
    implementation: the tree must come back, **and** the interrupt must still
    stop the program. Swallowing a Ctrl-C to tidy up is its own defect.
    """
    corpora, goldens, before = _two_corpus_record_fixture(tmp_path, monkeypatch)
    calls = {"n": 0}
    monkeypatch.setattr(
        golden_gate.os,
        "replace",
        _replace_failing_on(calls, {2: KeyboardInterrupt()}),
    )

    with pytest.raises(KeyboardInterrupt):
        golden_gate.record(corpora)

    # At least the two commits; the rollback restores through os.replace as well.
    assert calls["n"] >= 2, "the probe never reached the second replacement"
    for name, path in goldens.items():
        assert path.read_bytes() == before[name], (
            f"{name}.json was left rewritten after the run was interrupted"
        )
    assert not list(tmp_path.glob(".*")), "a staged temporary was left behind"


def test_a_replacement_that_succeeded_before_the_interrupt_is_still_rolled_back(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The window between a successful replace and the record of it.

    ``os.replace`` returning is not the same instant as the bookkeeping that
    says it returned, and an interrupt can be delivered in between. A list
    appended to *after* the call would not know that file had changed, so the
    rollback would skip it and leave exactly one golden updated — the failure
    this entire function exists to prevent, reached through a gap of one
    bytecode instruction.

    The probe performs the real replacement and *then* raises, which is the only
    way to tell pre-tracking from post-tracking: under post-tracking the second
    file is genuinely rewritten and stays that way.
    """
    corpora, goldens, before = _two_corpus_record_fixture(tmp_path, monkeypatch)
    calls = {"n": 0}
    monkeypatch.setattr(
        golden_gate.os,
        "replace",
        _replace_failing_on(calls, {2: KeyboardInterrupt()}, perform_first=frozenset({2})),
    )

    with pytest.raises(KeyboardInterrupt):
        golden_gate.record(corpora)

    for name, path in goldens.items():
        assert path.read_bytes() == before[name], (
            f"{name}.json was replaced before the interrupt and never rolled back"
        )
    assert not list(tmp_path.glob(".*")), "a staged temporary was left behind"


def test_an_interrupt_names_the_files_a_failed_rollback_could_not_restore(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An interrupt is the exception the operator actually sees, so it carries the news.

    The I/O path already reported an incomplete rollback. The interrupt path
    computed the same answer and threw it away — so a Ctrl-C that left a golden
    rewritten propagated a bare ``KeyboardInterrupt``, which reads exactly like
    the clean case. Two exits describing one tree, and only one of them
    describing it.
    """
    corpora, goldens, _before = _two_corpus_record_fixture(tmp_path, monkeypatch)
    calls = {"n": 0}
    monkeypatch.setattr(
        golden_gate.os,
        "replace",
        _replace_failing_on(
            calls,
            {
                2: KeyboardInterrupt(),
                # The rollback of the first golden, which cannot be put back.
                3: OSError(13, "Permission denied", str(goldens["first"])),
            },
        ),
    )

    with pytest.raises(KeyboardInterrupt) as raised:
        golden_gate._commit_goldens(
            [(corpus, b'{"payload": true}\n') for corpus in corpora]
        )

    notes = getattr(raised.value, "__notes__", [])
    assert any("INCONSISTENT" in note for note in notes), (
        f"the interrupt said nothing about the incomplete rollback: {notes}"
    )
    assert any("first.json" in note for note in notes), notes


def test_a_failed_rollback_is_reported_rather_than_described_as_clean(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The one thing the error message may never do is claim a false all-clear.

    When restoration itself fails the tree really is inconsistent, and saying
    "the committed set is unchanged" there would be the single sentence that
    stops somebody going and looking. The message has to name what could not be
    put back, and point at the command that shows it.
    """
    corpora, goldens, _before = _two_corpus_record_fixture(tmp_path, monkeypatch)
    calls = {"n": 0}
    monkeypatch.setattr(
        golden_gate.os,
        "replace",
        _replace_failing_on(
            calls,
            {
                # The commit of the second golden, then the rollback of the first.
                2: OSError(28, "No space left on device", str(goldens["second"])),
                3: OSError(13, "Permission denied", str(goldens["first"])),
            },
        ),
    )

    with pytest.raises(GoldenError) as raised:
        golden_gate._commit_goldens(
            [(corpus, b'{"payload": true}\n') for corpus in corpora]
        )

    message = str(raised.value)
    assert "INCONSISTENT" in message, message
    assert "first.json" in message, message
    assert "unchanged and still coherent" not in message, (
        "a failed rollback was described as a clean one"
    )
    assert not list(tmp_path.glob(".*")), "a staged temporary was left behind"


def test_a_format_one_golden_is_refused_rather_than_half_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An old golden carries no byte-level digest, so comparing it would lie.

    Format 1 recorded only the manifest-derived digests. Reading one with this
    tool and comparing the keys it happens to share would report clean while
    checking strictly less than the gate claims — a passing verdict that has
    quietly stopped covering the rendered bytes. Refusing is the only honest
    answer, and the message has to name the way out.
    """
    golden_path = tmp_path / "legacy.json"
    golden_path.write_text(
        json.dumps({"format": 1, "corpus": "legacy", "cases": {}}) + "\n", encoding="utf-8"
    )
    monkeypatch.setattr(Corpus, "golden", property(lambda self: golden_path))

    from golden_gate import _load_golden

    with pytest.raises(GoldenError, match="format 1") as raised:
        _load_golden(Corpus(name="legacy", tier=SUITE_TIER, why="probe"))
    assert "--record --only legacy" in str(raised.value)


def test_a_format_two_golden_is_refused_rather_than_assuming_one_root_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Format 2 cannot account by name for files outside case directories.

    Reading it as format 3 would silently restore the false one-root-file
    assumption. Refusal keeps the invariant strict and names the gate's safe,
    reproducibility-checked re-record path.
    """
    golden_path = tmp_path / "legacy.json"
    golden_path.write_text(
        json.dumps({"format": 2, "corpus": "legacy", "cases": {}}) + "\n", encoding="utf-8"
    )
    monkeypatch.setattr(Corpus, "golden", property(lambda self: golden_path))

    from golden_gate import _load_golden

    with pytest.raises(GoldenError, match="format 2") as raised:
        _load_golden(Corpus(name="legacy", tier=SUITE_TIER, why="probe"))
    assert "--record --only legacy" in str(raised.value)


def test_a_bare_record_is_a_usage_error(tmp_path: Path) -> None:
    """Re-recording accepts new output as correct, so the scope is stated.

    It is also the fastest way to turn a red gate green, which is exactly why it
    may not be the default: a reviewer seeing four rewritten goldens should be
    seeing a decision, not a reflex.

    The subprocess runs against the real golden directory, so this test must
    contain its own blast radius: if the usage-error guard is ever absent (the
    exact defect mutant m14-7 plants), the CLI proceeds to a REAL bare
    re-record. The snapshot/restore below confines that failure to a red
    assertion instead of silently restamping every golden in the working tree —
    which is precisely what happened on two mutation sweeps before this guard
    existed.

    The ``finally`` rollback is best-effort only: a SIGKILL or outer-timeout
    kill skips it entirely. The one-level copy is deliberate because the command
    contract is a flat golden directory, not a recursive subtree restore.
    """
    golden_dir = Path(__file__).parent / "golden"
    snapshot = tmp_path / "golden-snapshot"
    shutil.copytree(golden_dir, snapshot)
    try:
        completed = subprocess.run(
            [sys.executable, str(TOOL), "--record"],
            capture_output=True,
            text=True,
            check=False,
        )
        assert completed.returncode == 2, completed.stdout + completed.stderr
        assert "explicit scope" in completed.stderr
    finally:
        for path in snapshot.iterdir():
            shutil.copy2(path, golden_dir / path.name)
        for path in golden_dir.iterdir():
            if not (snapshot / path.name).exists():
                path.unlink()


def test_an_unknown_corpus_name_is_a_usage_error_not_an_empty_pass() -> None:
    """``--only typo`` must not check zero corpora and exit clean."""
    completed = subprocess.run(
        [sys.executable, str(TOOL), "--check", "--only", "no-such-corpus"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 2, completed.stdout + completed.stderr
    assert "unknown corpus" in completed.stderr


def test_a_missing_golden_is_reported_with_the_command_that_creates_it() -> None:
    """A gate that cannot find its baseline explains itself."""
    from golden_gate import _load_golden

    absent = Corpus(name="not-a-corpus", tier=SUITE_TIER, why="probe")
    with pytest.raises(GoldenError, match="--record --only not-a-corpus"):
        _load_golden(absent)


# ---------------------------------------------------------------------------
# The gate itself
# ---------------------------------------------------------------------------


@pytest.mark.slow
@requires_substrate
def test_the_suite_tier_corpora_are_byte_identical_to_their_goldens() -> None:
    """The invariant, enforced: same seed and engine, same bytes as when recorded.

    Regenerates the ``suite``-tier corpora through the shipped CLI in fresh
    processes, validates them, and compares every digest with the committed
    golden. The ``ci``-tier corpora are covered by their own CI step so that
    this stays around half a minute; see ``CORPORA`` for why the split is drawn
    there.

    A failure here is not a flake. Either something changed the output — in
    which case the report says which case and which axis — or a dependency
    moved, which the report also says. If the change was intended, re-record and
    commit the golden so the diff is reviewable.
    """
    completed = subprocess.run(
        [sys.executable, str(TOOL), "--check", "--tier", SUITE_TIER],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout[-6000:] + completed.stderr[-2000:]
